### ISSUE TITLE
Error when importing seaborn_altair

### ISSUE THREAD

**Issue by mariam16548** [Kitware/seaborn_altair#8]
When I tried to import this package using this command `import seaborn_altair as salt`, I ended up with the following error: 
For reference, I have the latest version of seaborn (0.12.2). 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 import seaborn_altair as salt

File ~/miniconda3/lib/python3.10/site-packages/seaborn_altair/__init__.py:1
----> 1 from .categorical import *

File ~/miniconda3/lib/python3.10/site-packages/seaborn_altair/categorical.py:8
      5 from scipy import stats
      7 from seaborn.categorical import _CategoricalStatPlotter
----> 8 from seaborn.categorical import _CategoricalScatterPlotter
      9 from seaborn.palettes import color_palette
     10 from seaborn.external.six import string_types

ImportError: cannot import name '_CategoricalScatterPlotter' from 'seaborn.categorical' (/Users/mariamb/miniconda3/lib/python3.10/site-packages/seaborn/categorical.py)
```

**Comment by jeffbaumes** [comment]
This is an issue relating to the fact that seaborn has been updated quite a bit while this project has not been updated or maintained for several years. Someone would need to go through the example notebooks in this repo and make code updates to get them all working again which would take quite a bit of work.

I've also noticed that the pip-installable version of this library is not the latest from this GitHub repository, so to get the latest you'd need to check out this repo and run `pip install -e .`. But I did notice that your error appears in the most recent GitHub version as well (as well as scipy not being listed in the dependencies, it currently needs to be installed manually).
